### ISSUE TITLE
why is the mobile menu not working?

### ISSUE THREAD

**Issue by peach93** [subwaymatch/typefolio#3]
Hey, I've finished in modifying the template for my needs and now I want to upload it to a server. While testing everything before uploading I've recognized that my mobile menu isn't visible or isn't working :( 
Is it cause I've not uploaded the site yet?

Thanks for your help,
Carolin

**Comment by subwaymatch** [comment]
Your mobile menu should work without uploading it to a server. Can you provide me a preview URL? I can take a look.

**Comment by chikizz** [comment]
Hello, I really like the template and I'm starting to use the template , but also have a problem with navigation on mobiles . As you can fix ? Thank you!

**Comment by subwaymatch** [comment]
@chikizz Can you please describe the issue on your mobile view?

**Comment by chikizz** [comment]
Even I'm starting , but by reducing the screen to check Responsive navigation is not there to carry it up to make it look ? Because in the example is online if the navigation is . Thanks for answering
